### ISSUE TITLE
Deprecate this project

### ISSUE THREAD

**Issue by jounik** [vaadin/components-examples#15]
Make sure examples work with HTTPS (needed if we serve the examples from cdn.vaadin.com).

Use this URL for secure requests: https://randomuser.me/api/?results=1

**Comment by tepi** [comment]
Review the HTTP/HTTPS fix at: https://github.com/vaadin/vaadin-grid/pull/154

Deprecation can be done only when we have a working demo available on CDN.

**Comment by manolo** [comment]
Duplicated of vaadin/vaadin-components#4
